import type { ScheduledJob } from './types';

const BASE = '2026-05-20T08:00:00Z';

/** Spec §8 — ilk store yüklemesinde seed */
export const DEFAULT_SCHEDULED_JOBS: Omit<ScheduledJob, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    code: 'agent_reconciliation_email',
    name: 'Agent Mutabakat E-postası',
    description: 'Temsilci mutabakat özet e-postası (mock)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 8 * * *',
    owner: 'Sistem',
    serviceUrl: 'internal://agent-reconciliation-email',
    dependencyIds: [],
    maxRetry: 3,
    retryIntervalSec: 60,
    payload: '{}',
    feedbackEmail: 'ops@epay.local',
  },
  {
    code: 'sanction_screening_monthly',
    name: 'Aylık Yaptırım Taraması',
    description: 'Müşteri yaptırım listesi taraması (stub)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 2 1 * *',
    owner: 'Uyum',
    serviceUrl: 'internal://sanction-screening-monthly',
    dependencyIds: [],
    maxRetry: 2,
    retryIntervalSec: 120,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'unblock_expired_entities',
    name: 'Süresi Dolan Blokaj Kaldırma',
    description: 'Geçici blokaj süresi dolan kayıtlar (stub)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 1 * * *',
    owner: 'Operasyon',
    serviceUrl: 'internal://unblock-expired-entities',
    dependencyIds: [],
    maxRetry: 3,
    retryIntervalSec: 60,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'expire_fees_campaigns',
    name: 'Ücret ve Kampanya Süre Sonu',
    description: 'Müşteri/temsilci ücret ve kampanya batch expire',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 2 * * *',
    owner: 'Finans',
    serviceUrl: 'internal://expire-fees-campaigns',
    dependencyIds: [],
    maxRetry: 3,
    retryIntervalSec: 90,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'agent_avg_fee_stats',
    name: 'Temsilci Ortalama Ücret İstatistiği',
    description: 'Temsilci ücret ortalaması hesaplama (stub)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 3 * * *',
    owner: 'Finans',
    serviceUrl: 'internal://agent-avg-fee-stats',
    dependencyIds: [],
    maxRetry: 2,
    retryIntervalSec: 60,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'dms_archive_expired',
    name: 'DMS Süresi Dolan Arşiv',
    description: 'Saklama süresi dolan doküman arşivi (stub)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 4 * * *',
    owner: 'DMS',
    serviceUrl: 'internal://dms-archive-expired',
    dependencyIds: [],
    maxRetry: 3,
    retryIntervalSec: 120,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'dms_integrity_monthly',
    name: 'DMS Aylık Bütünlük Kontrolü',
    description: 'Doküman hash bütünlük taraması (stub)',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 5 1 * *',
    owner: 'DMS',
    serviceUrl: 'internal://dms-integrity-monthly',
    dependencyIds: [],
    maxRetry: 2,
    retryIntervalSec: 300,
    payload: '{}',
    feedbackEmail: null,
  },
  {
    code: 'tcmb_daily_reports',
    name: 'TCMB Günlük Rapor Batch',
    description: 'Günlük komisyon ve mutabakat envanter raporları',
    status: 'Active',
    jobType: 'Recurring',
    cronExpression: '0 6 * * *',
    owner: 'Finans',
    serviceUrl: 'internal://tcmb-daily-reports',
    dependencyIds: [],
    maxRetry: 3,
    retryIntervalSec: 180,
    payload: '{"reportDate":"2026-05-24"}',
    feedbackEmail: 'reports@epay.local',
  },
];

export function seedDefaultJobRow(
  def: (typeof DEFAULT_SCHEDULED_JOBS)[number],
  index: number,
): ScheduledJob {
  const now = BASE;
  return {
    ...def,
    id: `job-${String(index + 1).padStart(3, '0')}`,
    createdAt: now,
    updatedAt: now,
  };
}
