import type { IntegrationDefinition } from './types';

const USER = 'mgmt-user';
const TS = '2026-05-21T08:00:00Z';

function base(
  partial: Omit<IntegrationDefinition, 'id' | 'code' | 'credentialRef' | 'createdAt' | 'createdBy' | 'updatedAt' | 'updatedBy'>,
  id: string,
  code: string,
): Omit<IntegrationDefinition, 'credentialRef'> {
  return {
    ...partial,
    id,
    code,
    createdAt: TS,
    createdBy: USER,
    updatedAt: TS,
    updatedBy: USER,
  };
}

export const DEFAULT_INTEGRATIONS: Omit<IntegrationDefinition, 'credentialRef'>[] = [
  base(
    {
      name: 'ERP Muhasebe',
      integrationType: 'Accounting',
      systemName: 'Logo/Netsis',
      status: 'Active',
      description: 'Muhasebe fiş entegrasyonu — 8.3',
      baseUrl: 'https://erp-mock.epay.local/api',
      authType: 'ApiKey',
      keyRotationRequired: true,
      timeoutMs: 30_000,
      connectionTimeoutMs: 5000,
      ipAllowlist: '10.0.0.0/8',
      tlsInfo: 'TLS 1.2, corp CA',
      rateLimitPerMin: 120,
      retryPolicy: 'ExponentialBackoff',
      maxRetry: 5,
      fixedDelayMs: 1000,
      useSignature: true,
      webhookUrl: null,
      apiVersion: 'v2',
      circuitBreakerEnabled: true,
      errorRateThresholdPct: 50,
      windowSeconds: 60,
      minRequestCount: 5,
      openDurationSeconds: 30,
      logLevel: 'Info',
    },
    'int-001',
    'erp_accounting',
  ),
  base(
    {
      name: 'BTRANS GİB',
      integrationType: 'Btrans',
      systemName: 'GİB',
      status: 'Active',
      description: 'BTRANS rapor gönderimi — 8.4',
      baseUrl: 'https://gib-mock.epay.local/btrans',
      authType: 'MutualTls',
      keyRotationRequired: true,
      timeoutMs: 60_000,
      connectionTimeoutMs: 8000,
      ipAllowlist: '',
      tlsInfo: 'mTLS client cert',
      rateLimitPerMin: 30,
      retryPolicy: 'FixedDelay',
      maxRetry: 3,
      fixedDelayMs: 2000,
      useSignature: true,
      webhookUrl: 'https://epay.local/hooks/btrans',
      apiVersion: '2024.1',
      circuitBreakerEnabled: false,
      errorRateThresholdPct: null,
      windowSeconds: null,
      minRequestCount: null,
      openDurationSeconds: null,
      logLevel: 'Warning',
    },
    'int-002',
    'btrans_gib',
  ),
  base(
    {
      name: 'TCMB Kur',
      integrationType: 'FxRate',
      systemName: 'TCMB',
      status: 'Active',
      description: 'Günlük kur çekimi — 8.6',
      baseUrl: 'https://tcmb-mock.epay.local/rates',
      authType: 'None',
      keyRotationRequired: false,
      timeoutMs: 15_000,
      connectionTimeoutMs: 3000,
      ipAllowlist: '',
      tlsInfo: '',
      rateLimitPerMin: 60,
      retryPolicy: 'FixedDelay',
      maxRetry: 2,
      fixedDelayMs: 1000,
      useSignature: false,
      webhookUrl: null,
      apiVersion: 'v1',
      circuitBreakerEnabled: false,
      errorRateThresholdPct: null,
      windowSeconds: null,
      minRequestCount: null,
      openDurationSeconds: null,
      logLevel: 'Info',
    },
    'int-003',
    'tcmb_fx',
  ),
  base(
    {
      name: 'Banka API',
      integrationType: 'Banking',
      systemName: 'BankX',
      status: 'Active',
      description: 'Banka hareket senkronu — 6.x',
      baseUrl: 'https://bankx-mock.epay.local',
      authType: 'OAuth2',
      keyRotationRequired: false,
      timeoutMs: 20_000,
      connectionTimeoutMs: 5000,
      ipAllowlist: '192.168.0.0/16',
      tlsInfo: 'TLS 1.3',
      rateLimitPerMin: 200,
      retryPolicy: 'ExponentialBackoff',
      maxRetry: 4,
      fixedDelayMs: 800,
      useSignature: false,
      webhookUrl: null,
      apiVersion: '3.0',
      circuitBreakerEnabled: true,
      errorRateThresholdPct: 40,
      windowSeconds: 120,
      minRequestCount: 10,
      openDurationSeconds: 60,
      logLevel: 'Debug',
    },
    'int-004',
    'bank_api',
  ),
  base(
    {
      name: 'KYC Screening',
      integrationType: 'Kyc',
      systemName: 'SanctionProvider',
      status: 'Active',
      description: 'Yaptırım taraması — 8.2',
      baseUrl: 'https://kyc-mock.epay.local/screen',
      authType: 'ApiKey',
      keyRotationRequired: true,
      timeoutMs: 25_000,
      connectionTimeoutMs: 5000,
      ipAllowlist: '',
      tlsInfo: '',
      rateLimitPerMin: 90,
      retryPolicy: 'FixedDelay',
      maxRetry: 2,
      fixedDelayMs: 1500,
      useSignature: true,
      webhookUrl: null,
      apiVersion: 'v1',
      circuitBreakerEnabled: false,
      errorRateThresholdPct: null,
      windowSeconds: null,
      minRequestCount: null,
      openDurationSeconds: null,
      logLevel: 'Info',
    },
    'int-005',
    'kyc_screen',
  ),
  base(
    {
      name: 'SMS Gateway',
      integrationType: 'Sms',
      systemName: 'Netgsm',
      status: 'Active',
      description: '12.6 SMS sağlayıcı',
      baseUrl: 'https://sms-mock.epay.local/send',
      authType: 'ApiKey',
      keyRotationRequired: false,
      timeoutMs: 10_000,
      connectionTimeoutMs: 3000,
      ipAllowlist: '',
      tlsInfo: '',
      rateLimitPerMin: 300,
      retryPolicy: 'FixedDelay',
      maxRetry: 3,
      fixedDelayMs: 500,
      useSignature: false,
      webhookUrl: null,
      apiVersion: '1',
      circuitBreakerEnabled: false,
      errorRateThresholdPct: null,
      windowSeconds: null,
      minRequestCount: null,
      openDurationSeconds: null,
      logLevel: 'Warning',
    },
    'int-006',
    'sms_gateway',
  ),
  base(
    {
      name: 'SMTP Relay',
      integrationType: 'Email',
      systemName: 'SMTP',
      status: 'Active',
      description: '12.6 e-posta sağlayıcı',
      baseUrl: 'https://relay-mock.epay.local:587',
      authType: 'ApiKey',
      keyRotationRequired: false,
      timeoutMs: 12_000,
      connectionTimeoutMs: 4000,
      ipAllowlist: '',
      tlsInfo: 'STARTTLS',
      rateLimitPerMin: 180,
      retryPolicy: 'FixedDelay',
      maxRetry: 2,
      fixedDelayMs: 1000,
      useSignature: false,
      webhookUrl: null,
      apiVersion: '1',
      circuitBreakerEnabled: false,
      errorRateThresholdPct: null,
      windowSeconds: null,
      minRequestCount: null,
      openDurationSeconds: null,
      logLevel: 'Info',
    },
    'int-007',
    'smtp_relay',
  ),
];
