export {
  CUSTOMER_PORTAL_TRANSACTION_STATUSES as TRANSACTION_STATUSES,
  PAYMENT_PURPOSES,
  paymentPurposeI18nKey,
  COMPLAINT_TYPES,
  complaintTypeI18nKey,
  EDUCATION_LEVELS,
  educationLevelI18nKey,
  EMPLOYMENT_CATEGORIES,
  employmentCategoryI18nKey,
  TRANSFER_CURRENCY_OPTIONS as TRANSFER_CURRENCIES,
  COUNTRIES,
} from '@epay/domain';
