import type { BackOfficeRole } from '@epay/ui';
import type { DocumentCategory } from '@/features/document-review/domain/types';
import type { DocumentTypeMaster } from './types';

type SeedRow = Omit<DocumentTypeMaster, 'recordStatus'>;

function row(partial: SeedRow): DocumentTypeMaster {
  return { ...partial, recordStatus: 1 };
}

const compView: BackOfficeRole[] = ['compliance', 'management'];
const compApprove: BackOfficeRole[] = ['compliance'];

/** Spec §8 — 7 kategori asgari standart tür seti */
export const STANDARD_DOCUMENT_TYPES: DocumentTypeMaster[] = [
  row({
    id: 'DT-IDCARD',
    documentCategory: 'Identity',
    documentTypeCode: 'IDCARD',
    name: 'TC Kimlik Kartı (Ön)',
    description: 'Kimlik ön yüz',
    activeRetentionYears: 5,
    archiveRetentionYears: 10,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['compliance', 'ops'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-IDCARD-BACK',
    documentCategory: 'Identity',
    documentTypeCode: 'IDCARD_BACK',
    name: 'TC Kimlik Kartı (Arka)',
    description: 'Kimlik arka yüz',
    activeRetentionYears: 5,
    archiveRetentionYears: 10,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['compliance', 'ops'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-PASSPORT',
    documentCategory: 'Identity',
    documentTypeCode: 'PASSPORT',
    name: 'Pasaport',
    description: 'Uluslararası kimlik',
    activeRetentionYears: 5,
    archiveRetentionYears: 10,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['compliance'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-ADDRESS',
    documentCategory: 'ProofOfAddress',
    documentTypeCode: 'ADDRESS',
    name: 'İkametgah Belgesi',
    description: 'Adres kanıtı',
    activeRetentionYears: 5,
    archiveRetentionYears: 10,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['compliance', 'ops'],
    viewerRoles: ['compliance', 'ops', 'management'],
    approverRoles: ['compliance', 'ops'],
  }),
  row({
    id: 'DT-INVOICE',
    documentCategory: 'ProofOfAddress',
    documentTypeCode: 'INVOICE',
    name: 'Fatura',
    description: 'Adres doğrulama faturası',
    activeRetentionYears: 3,
    archiveRetentionYears: 7,
    maxFileSizeMb: 10,
    isPersonalData: false,
    approvalRequired: true,
    uploaderRoles: ['compliance', 'ops'],
    viewerRoles: ['compliance', 'ops', 'management'],
    approverRoles: ['compliance', 'ops'],
  }),
  row({
    id: 'DT-PAYSLIP',
    documentCategory: 'ProofOfFunds',
    documentTypeCode: 'PAYSLIP',
    name: 'Maaş Bordrosu',
    description: 'Gelir kanıtı',
    activeRetentionYears: 3,
    archiveRetentionYears: 7,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: false,
    uploaderRoles: ['finance', 'compliance'],
    viewerRoles: ['finance', 'compliance', 'management'],
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-BANKSTMT',
    documentCategory: 'ProofOfFunds',
    documentTypeCode: 'BANKSTMT',
    name: 'Banka Ekstresi',
    description: 'Hesap hareketleri',
    activeRetentionYears: 5,
    archiveRetentionYears: 10,
    maxFileSizeMb: 15,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['finance', 'compliance'],
    viewerRoles: ['finance', 'compliance', 'management'],
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-LEGAL-TAX',
    documentCategory: 'LegalEntity',
    documentTypeCode: 'TAXCERT',
    name: 'TaxCertificate',
    description: 'Vergi levhası',
    activeRetentionYears: 10,
    archiveRetentionYears: 15,
    maxFileSizeMb: 15,
    isPersonalData: false,
    approvalRequired: true,
    uploaderRoles: ['compliance'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-TRADE-REG',
    documentCategory: 'LegalEntity',
    documentTypeCode: 'TRADEREG',
    name: 'TradeRegistryGazette',
    description: 'Ticaret sicil gazetesi',
    activeRetentionYears: 10,
    archiveRetentionYears: 20,
    maxFileSizeMb: null,
    isPersonalData: false,
    approvalRequired: true,
    uploaderRoles: ['compliance'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
  row({
    id: 'DT-TX-DECONT',
    documentCategory: 'ProofOfTransaction',
    documentTypeCode: 'TXDECONT',
    name: 'İmzalı Dekont',
    description: 'İşlem dekontu',
    activeRetentionYears: 7,
    archiveRetentionYears: 12,
    maxFileSizeMb: 10,
    isPersonalData: false,
    approvalRequired: false,
    uploaderRoles: ['ops'],
    viewerRoles: ['ops', 'compliance', 'management'],
    approverRoles: ['compliance', 'ops'],
  }),
  row({
    id: 'DT-AGREEMENT',
    documentCategory: 'Agreement',
    documentTypeCode: 'AGREEMENT',
    name: 'Müşteri Sözleşmesi',
    description: 'Çerçeve sözleşme',
    activeRetentionYears: 8,
    archiveRetentionYears: 15,
    maxFileSizeMb: 10,
    isPersonalData: false,
    approvalRequired: true,
    uploaderRoles: ['ops', 'compliance'],
    viewerRoles: ['ops', 'compliance', 'management'],
    approverRoles: ['compliance', 'ops'],
  }),
  row({
    id: 'DT-HR-CONTRACT',
    documentCategory: 'EmployeeHR',
    documentTypeCode: 'HRCONTRACT',
    name: 'İş Sözleşmesi',
    description: 'Personel iş sözleşmesi',
    activeRetentionYears: 6,
    archiveRetentionYears: 20,
    maxFileSizeMb: 10,
    isPersonalData: true,
    approvalRequired: true,
    uploaderRoles: ['compliance'],
    viewerRoles: compView,
    approverRoles: compApprove,
  }),
];

export const STANDARD_CATEGORIES: DocumentCategory[] = [
  'Identity',
  'ProofOfAddress',
  'ProofOfFunds',
  'LegalEntity',
  'ProofOfTransaction',
  'Agreement',
  'EmployeeHR',
];

export function categoriesInStandardSeed(): DocumentCategory[] {
  const set = new Set(STANDARD_DOCUMENT_TYPES.map((t) => t.documentCategory));
  return STANDARD_CATEGORIES.filter((c) => set.has(c));
}
