import type { ReportDefinition } from './types';

export const REPORT_CATALOG: ReportDefinition[] = [
  {
    code: 'financial_transactions',
    category: 'operational',
    titleKey: 'rpt_financial_transactions',
    descriptionKey: 'rpt_financial_transactions_desc',
    columnSummaryKeys: ['rpt_col_tx_no', 'rpt_col_amount_try'],
  },
  {
    code: 'error_transactions',
    category: 'operational',
    titleKey: 'rpt_error_transactions',
    descriptionKey: 'rpt_error_transactions_desc',
    columnSummaryKeys: ['rpt_col_tx_no', 'rpt_col_status'],
  },
  {
    code: 'risk_compliance_summary',
    category: 'operational',
    titleKey: 'rpt_risk_compliance_summary',
    descriptionKey: 'rpt_risk_compliance_summary_desc',
    columnSummaryKeys: ['rpt_col_case_id', 'rpt_col_status'],
  },
  {
    code: 'agent_accounts',
    category: 'operational',
    titleKey: 'rpt_agent_accounts',
    descriptionKey: 'rpt_agent_accounts_desc',
    columnSummaryKeys: ['rpt_col_agent', 'rpt_col_balance_try'],
  },
  {
    code: 'rejected_cancelled_corrections',
    category: 'operational',
    titleKey: 'rpt_rejected_cancelled',
    descriptionKey: 'rpt_rejected_cancelled_desc',
    columnSummaryKeys: ['rpt_col_tx_no', 'rpt_col_status'],
  },
  {
    code: 'system_errors',
    category: 'operational',
    titleKey: 'rpt_system_errors',
    descriptionKey: 'rpt_system_errors_desc',
    columnSummaryKeys: ['rpt_col_source', 'rpt_col_message'],
  },
  {
    code: 'daily_commission_fees',
    category: 'tcmb',
    titleKey: 'rpt_daily_commission_fees',
    descriptionKey: 'rpt_daily_commission_fees_desc',
    requiresReportDate: true,
    columnSummaryKeys: ['rpt_col_fee_try', 'rpt_col_currency'],
  },
  {
    code: 'daily_reconciliation_inventory',
    category: 'tcmb',
    titleKey: 'rpt_daily_reconciliation_inventory',
    descriptionKey: 'rpt_daily_reconciliation_inventory_desc',
    requiresReportDate: true,
    columnSummaryKeys: ['rpt_col_reference', 'rpt_col_case_no'],
  },
  {
    code: 'protection_account',
    category: 'tcmb',
    titleKey: 'rpt_protection_account',
    descriptionKey: 'rpt_protection_account_desc',
    requiresReportDate: true,
    columnSummaryKeys: ['rpt_col_balance_try'],
  },
  {
    code: 'transaction_volume_stats',
    category: 'tcmb',
    titleKey: 'rpt_transaction_volume_stats',
    descriptionKey: 'rpt_transaction_volume_stats_desc',
    columnSummaryKeys: ['rpt_col_channel', 'rpt_col_count'],
  },
  {
    code: 'entity_kyc_summary',
    category: 'tcmb',
    titleKey: 'rpt_entity_kyc_summary',
    descriptionKey: 'rpt_entity_kyc_summary_desc',
    columnSummaryKeys: ['rpt_col_entity', 'rpt_col_kyc'],
  },
  {
    code: 'str_output',
    category: 'masak',
    titleKey: 'rpt_str_output',
    descriptionKey: 'rpt_str_output_desc',
    columnSummaryKeys: ['rpt_col_case_id', 'rpt_col_str_ref'],
  },
  {
    code: 'info_document_response_pack',
    category: 'masak',
    titleKey: 'rpt_info_document_pack',
    descriptionKey: 'rpt_info_document_pack_desc',
    columnSummaryKeys: ['rpt_col_request_id', 'rpt_col_status'],
  },
  {
    code: 'asset_freeze_sanctions_summary',
    category: 'masak',
    titleKey: 'rpt_asset_freeze',
    descriptionKey: 'rpt_asset_freeze_desc',
    columnSummaryKeys: ['rpt_col_entity', 'rpt_col_sanction'],
  },
];
