import type { ParameterCatalogEntry } from './types';

/** Katalog tanımları — yeni kayıt yalnızca katalogdaki anahtarlardan seçilebilir */
export const PARAMETER_CATALOG: ParameterCatalogEntry[] = [
  {
    parameterKey: 'upload_limits.default_max_file_size_mb',
    groupName: 'upload_limits',
    valueType: 'number',
    defaultValue: '10',
    descriptionKey: 'prm_desc_default_max_file_size_mb',
    min: 1,
    max: 500,
  },
  {
    parameterKey: 'upload_limits.max_upload_size_mb',
    groupName: 'upload_limits',
    valueType: 'number',
    defaultValue: '25',
    descriptionKey: 'prm_desc_max_upload_size_mb',
    min: 1,
    max: 500,
  },
  {
    parameterKey: 'reconciliation.amount_tolerance_try',
    groupName: 'reconciliation',
    valueType: 'number',
    defaultValue: '0.01',
    descriptionKey: 'prm_desc_amount_tolerance_try',
    min: 0,
    max: 1_000_000,
  },
  {
    parameterKey: 'reconciliation.date_tolerance_hours',
    groupName: 'reconciliation',
    valueType: 'number',
    defaultValue: '1',
    descriptionKey: 'prm_desc_date_tolerance_hours',
    min: 0,
    max: 168,
  },
  {
    parameterKey: 'reconciliation.unmatched_urgency_threshold_try',
    groupName: 'reconciliation',
    valueType: 'number',
    defaultValue: '10000',
    descriptionKey: 'prm_desc_unmatched_urgency_threshold_try',
    min: 0,
    max: 100_000_000,
  },
  {
    parameterKey: 'fraud.engine_timeout_ms',
    groupName: 'fraud',
    valueType: 'duration_ms',
    defaultValue: '-1',
    descriptionKey: 'prm_desc_engine_timeout_ms',
    approvalOnChange: true,
    criticalZeroConfirm: true,
  },
  {
    parameterKey: 'fx.rate_cache_ttl_minutes',
    groupName: 'fx',
    valueType: 'number',
    defaultValue: '15',
    descriptionKey: 'prm_desc_rate_cache_ttl_minutes',
    min: 1,
    max: 1440,
  },
  {
    parameterKey: 'treasury.reserve_max_amount_try',
    groupName: 'treasury',
    valueType: 'number',
    defaultValue: '5000000',
    descriptionKey: 'prm_desc_reserve_max_amount_try',
    min: 0,
    max: 1_000_000_000,
    approvalOnChange: true,
  },
  {
    parameterKey: 'otp.rate_limit_per_hour',
    groupName: 'otp',
    valueType: 'number',
    defaultValue: '5',
    descriptionKey: 'prm_desc_rate_limit_per_hour',
    min: 1,
    max: 100,
  },
  {
    parameterKey: 'retry.default_max_retries',
    groupName: 'retry',
    valueType: 'number',
    defaultValue: '3',
    descriptionKey: 'prm_desc_default_max_retries',
    min: 0,
    max: 20,
    approvalOnChange: true,
  },
  {
    parameterKey: 'approval.max_report_date_range_days',
    groupName: 'approval',
    valueType: 'number',
    defaultValue: '365',
    descriptionKey: 'prm_desc_max_report_date_range_days',
    min: 1,
    max: 3650,
  },
  {
    parameterKey: 'hr.annual_entitlement_days',
    groupName: 'hr',
    valueType: 'number',
    defaultValue: '14',
    descriptionKey: 'prm_desc_annual_entitlement_days',
    min: 0,
    max: 60,
  },
  {
    parameterKey: 'hr.sick_leave_limit_days',
    groupName: 'hr',
    valueType: 'number',
    defaultValue: '10',
    descriptionKey: 'prm_desc_sick_leave_limit_days',
    min: 0,
    max: 365,
  },
  {
    parameterKey: 'hr.leave_report_max_rows',
    groupName: 'hr',
    valueType: 'number',
    defaultValue: '500',
    descriptionKey: 'prm_desc_leave_report_max_rows',
    min: 100,
    max: 100_000,
  },
  {
    parameterKey: 'hr.public_holidays',
    groupName: 'hr',
    valueType: 'string',
    defaultValue:
      '["2026-01-01","2026-04-23","2026-05-01","2026-05-19","2026-07-15","2026-08-30","2026-10-29"]',
    descriptionKey: 'prm_desc_public_holidays',
  },
  {
    parameterKey: 'approval.pool_refresh_interval_seconds',
    groupName: 'approval',
    valueType: 'number',
    defaultValue: '30',
    descriptionKey: 'prm_desc_pool_refresh_interval_seconds',
    min: 5,
    max: 600,
    seed: false,
  },
  {
    parameterKey: 'retry.backoff_base_ms',
    groupName: 'retry',
    valueType: 'duration_ms',
    defaultValue: '1000',
    descriptionKey: 'prm_desc_backoff_base_ms',
    min: 100,
    max: 60_000,
    seed: false,
  },
];

export const PARAMETER_GROUPS = [
  'upload_limits',
  'reconciliation',
  'fraud',
  'fx',
  'treasury',
  'otp',
  'retry',
  'approval',
  'hr',
] as const;

export function getCatalogEntry(key: string): ParameterCatalogEntry | undefined {
  return PARAMETER_CATALOG.find((e) => e.parameterKey === key);
}

export function getCreatableCatalogEntries(activeKeys: ReadonlySet<string>): ParameterCatalogEntry[] {
  return PARAMETER_CATALOG.filter((e) => !activeKeys.has(e.parameterKey));
}
